---

- name: install/uninstall/configure docker
  hosts: docker
  roles:
    - docker
  tags:
    - docker-install


- name: install/uninstall/configure docker-compose
  hosts: docker
  roles:
    - docker-compose
  tags:
    - docker-compose-install


- name: install/uninstall docker-machine
  hosts: docker
  roles:
    - docker-machine
  tags:
    - docker-machine-install
