---
# default

# proxy connections (mandatory)
proxy_env:
  foo: bar
#  http_proxy: http://x.x.x.x:80


# repository url
apt_list_docker_url: "https://download.docker.com/linux"


# user list to add to the 'docker' group
user2dockergroup: [ 'foo' ]
