---
# roles/docker/tasks/sysinit.yml

- name: is initsystem among SysV or Systemd
  shell: stat /proc/1/exe
  register: init_system


- name: with 'systemd' - create /etc/systemd/system/docker.service.d directory
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
    recurse: no
  when: (proxy_env['http_proxy'] is defined) and (proxy_env['http_proxy'] != '') and (init_system.stdout.find('systemd') != -1)


- name:  with 'systemd' - create /etc/systemd/system/docker.service.d/http-proxy.conf file
  lineinfile:
    state: present
    create: yes
    owner: "root"
    group: "root"
    mode: 0644
    dest: "/etc/systemd/system/docker.service.d/http-proxy.conf"
    line: "{{ item }}"
  with_items:
    - "[Service]"
    - "Environment=\"HTTP_PROXY={{ proxy_env['http_proxy'] | default(omit) }}\""
  when: (proxy_env['http_proxy'] is defined) and (proxy_env['http_proxy'] != '') and (init_system.stdout.find('systemd') != -1)


- name: reload systemd
  command: systemctl daemon-reload
  when: (proxy_env['http_proxy'] is defined) and (proxy_env['http_proxy'] != '') and (init_system.stdout.find('systemd') != -1)


- name: with 'init' - update /etc/default/docker file
  lineinfile:
    state: present
    create: no
    owner: "root"
    group: "root"
    mode: 0644
    insertafter: "export http_proxy"
    dest: "/etc/default/docker"
    line: "export http_proxy=\"{{ proxy_env['http_proxy'] }}\""
  when: (proxy_env['http_proxy'] is defined) and (proxy_env['http_proxy'] != '') and (init_system.stdout.find('init') != -1)
